### PR TITLE
Fix curl command again

### PR DESCRIPTION
**Pull request by Artoria2e5**
Human generally prefer escaping over quoting.

### CODE REVIEW

**Comment by magicnat** [comment]
You know, some osu! players aren't human. (
Especially those play osu! on OSX.
lol

**Comment by Artoria2e5** [comment]
In order to be further non-human, my suggestion is to use `printf '%(%s)T'` instead of `date +%s`... XD

**Comment by ghost** [comment]
Why are you making the curl command so complicated?

I'd just use something like:
`curl -SL# 'https://m1.ppy.sh/r/osu!.exe' -o osu.exe`

**Comment by peppy** [comment]
The request string was added because the executable can get cached otherwise, but I agree that focus is being placed on the wrong thing here. This was made open source to fix the actual bundle, not the script which won't even be included in the final distribution.

**Pull request closed without merging**
